name: Build Toolchain with Crosstool-NG

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc g++ gperf bison flex texinfo help2man make libncurses5-dev python3-dev autoconf automake libtool libtool-bin gawk wget bzip2 xz-utils unzip patch libstdc++6 rsync git meson ninja-build

      - name: Download crosstool-ng
        run: |
          wget http://crosstool-ng.org/download/crosstool-ng/crosstool-ng-1.26.0.tar.xz
          tar -xf crosstool-ng-1.26.0.tar.xz

      - name: Configure and build crosstool-ng
        run: |
          cd crosstool-ng-1.26.0
          ./configure --enable-local
          make

      - name: Configure and build toolchain
        run: |
          cd crosstool-ng-1.26.0
          cp ../config ./.config
          ./ct-ng build

      - name: Make toolchain archive
        run: |
          cd ~/x-tools
          tar -cjf armv6-unknown-linux-gnueabihf.tar.bz2 armv6-unknown-linux-gnueabihf

      - name: Archive toolchain artifacts
        uses: actions/upload-artifact@v4
        with:
          name: armv6-unknown-linux-gnueabihf
          path: ~/x-tools/armv6-unknown-linux-gnueabihf.tar.bz2
